### ISSUE TITLE
error on make install

### ISSUE THREAD

**Issue by chiragjp** [chiragjp/xwas#1]
Even as sudo, I get this:
R CMD install -l ~/.R_libs/ xwas_*.tar.gz
Error: ERROR: cannot cd to directory ‘/Users/cjp/.R_libs/’

**Comment by npho** [comment]
I put an update into the `README.md` file as well as the web version here,

http://www.chiragjpgroup.org/xwas/

Since I set `R_LIBS="~/.R_libs"` within the `~/.Renviron` file in my own setup, it will manage all user-installed packages locally within the users own `$HOME` directory. It's easier to isolate all user package development from the system deployment of R. If you run a `mkdir ~/.R_libs` and create the same `.Renviron` file with the `R_LIBS` entry then a `make deploy` should install fine.

The `devtools` install method also works, apologies on any confusion.
